name: kasiralex
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.17.0
  google_fonts: ^6.1.0
  dotted_border: ^2.0.0
  flutter_local_notifications: ^17.1.2
  google_maps_flutter: ^2.6.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
